version: '3.8'
services:
  web:
    env_file:
      - ./apps/web/.env.local
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "3001:3000" # host 3001 -> container 3000
    environment:
      NODE_ENV: production
      PORT: 3000
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/_next/static || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
  api:
    env_file:
      - ./apps/api/.env.local
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - "4000:4000" # host 4000 -> container 4000
    environment:
      NODE_ENV: production
      PORT: 4000
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: morpho_net
